name: "Lighthouse CI Reports"
description: "Run Lighthouse CI audits (mobile + desktop) and upload reports to GitHub Gists"

inputs:
  urls:
    description: "Comma-separated URLs to audit"
    required: true
  gh-token:
    description: "GitHub token for creating Gists"
    required: true
  number-of-runs:
    description: "Number of Lighthouse runs per URL"
    required: false
    default: "3"

outputs:
  results:
    description: "JSON array with all report results [{type, testUrl, viewerUrl, performance}]"
    value: ${{ steps.parse-results.outputs.results }}
  mobile-viewer-url:
    description: "Lighthouse viewer URL for the first mobile report (backwards compatibility)"
    value: ${{ steps.parse-results.outputs.mobile-viewer-url }}
  desktop-viewer-url:
    description: "Lighthouse viewer URL for the first desktop report (backwards compatibility)"
    value: ${{ steps.parse-results.outputs.desktop-viewer-url }}
  average-performance:
    description: "Average performance score across all reports"
    value: ${{ steps.parse-results.outputs.average-performance }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install pnpm and dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        corepack enable
        corepack prepare pnpm@9 --activate
        pnpm install --frozen-lockfile

    - name: Install Chrome
      shell: bash
      run: |
        if command -v google-chrome &> /dev/null; then
          echo "Chrome already installed: $(google-chrome --version)"
        elif command -v apt-get &> /dev/null; then
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
        elif command -v yum &> /dev/null; then
          sudo tee /etc/yum.repos.d/google-chrome.repo << 'REPO'
        [google-chrome]
        name=Google Chrome
        baseurl=https://dl.google.com/linux/chrome/rpm/stable/x86_64
        enabled=1
        gpgcheck=1
        gpgkey=https://dl.google.com/linux/linux_signing_key.pub
        REPO
          sudo yum install -y google-chrome-stable
        else
          echo "::error::Unsupported OS. Install Google Chrome manually on this runner."
          exit 1
        fi
        CHROME_BIN=$(which google-chrome)
        WRAPPER="/usr/local/bin/chrome-wrapper"
        cat > "$WRAPPER" << SCRIPT
        #!/bin/bash
        exec $CHROME_BIN --no-sandbox --disable-dev-shm-usage "\$@"
        SCRIPT
        chmod +x "$WRAPPER"
        echo "CHROME_PATH=$WRAPPER" >> $GITHUB_ENV
        echo "Chrome wrapper created at $WRAPPER"

    - name: Install LHCI
      shell: bash
      run: npm install -g @lhci/cli

    - name: Generate Lighthouse configs
      shell: bash
      working-directory: ${{ github.action_path }}
      run: node --loader ts-node/esm src/generate-config.ts "${{ inputs.urls }}" all "${{ inputs.number-of-runs }}"

    - name: Run Lighthouse CI (mobile)
      shell: bash
      run: lhci autorun --config="${{ github.action_path }}/.lighthouserc.mobile.json"

    - name: Run Lighthouse CI (desktop)
      shell: bash
      run: lhci autorun --config="${{ github.action_path }}/.lighthouserc.desktop.json"

    - name: Upload reports to Gists
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
      run: node --loader ts-node/esm src/action-entrypoint.ts ${{ github.workspace }}

    - name: Parse results and set outputs
      id: parse-results
      shell: bash
      run: |
        RESULTS=$(node -e "const r=JSON.parse(require('fs').readFileSync('results.json','utf8')); console.log(JSON.stringify(r.map(x=>({type:x.type,testUrl:x.testUrl,viewerUrl:x.viewerUrl,performance:x.performance}))))")
        MOBILE_URL=$(node -e "const r=JSON.parse(require('fs').readFileSync('results.json','utf8')); const m=r.find(x=>x.type==='mobile'); console.log(m?.viewerUrl||'')")
        DESKTOP_URL=$(node -e "const r=JSON.parse(require('fs').readFileSync('results.json','utf8')); const d=r.find(x=>x.type==='desktop'); console.log(d?.viewerUrl||'')")
        AVG=$(node -e "const r=JSON.parse(require('fs').readFileSync('results.json','utf8')); console.log(Math.round(r.reduce((s,x)=>s+x.performance,0)/r.length))")
        echo "results=$RESULTS" >> $GITHUB_OUTPUT
        echo "mobile-viewer-url=$MOBILE_URL" >> $GITHUB_OUTPUT
        echo "desktop-viewer-url=$DESKTOP_URL" >> $GITHUB_OUTPUT
        echo "average-performance=$AVG" >> $GITHUB_OUTPUT

    - name: Upload HTML reports as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lighthouse-reports
        path: .lighthouse-reports/**/*.report.html

    - name: Generate summary
      shell: bash
      run: |
        AVG=$(node -e "const r=JSON.parse(require('fs').readFileSync('results.json','utf8')); console.log(Math.round(r.reduce((s,x)=>s+x.performance,0)/r.length))")
        ROWS=$(node -e "
          const r=JSON.parse(require('fs').readFileSync('results.json','utf8'));
          r.forEach(x => {
            const perf = Math.round(x.performance);
            console.log('| ' + x.type + ' | ' + x.testUrl + ' | ' + perf + '% | [View Report](' + x.viewerUrl + ') |');
          });
        ")
        cat >> $GITHUB_STEP_SUMMARY << EOF
        ## Lighthouse CI Results

        | Device | URL | Performance | Viewer |
        |--------|-----|------------|--------|
        ${ROWS}

        **Average Performance: ${AVG}%**
        EOF
